### PR TITLE
Add headers to definitions

### PR DESCRIPTION
**Pull request by tobylad**
@Bontgoy

### CODE REVIEW

**Review by tobylad — COMMENTED** [review]
@majesty86

**Comment by Bontgoy** [comment]
@majesty86 Make sure that you are creating new branches for each assignment you do.  I should only see the git definitions changes in the pull request.

The web_basics challenge should be in s separate PR.

**Comment by tobylad** [comment]
@Bontgoy Will different branches have separate pull requests?  Also, are all our assignments going into our forked "phase-0-tracks" repository?  The issue I had that you mentioned above is exactly what I and @ncody ran into during our pair session today.  Still on damage control, but I think I may just re-create all the files in a new branch and push it that way.

**Comment by Bontgoy** [comment]
@majesty86 You should be making a separate branch for each new assignment.

You want to send submissions up to the phase-0-tracks repo that you own (The one you forked from github). So this is the correct location here.

If you and/or @ncody want to cover more ground on this reach out to me on Slack and we can have a group chat.

**Pull request merged**
